package com.npb.gp.domain.core;

/**
 * @author Dan Castillo
 * Date Created: 12/14/2012
 * @since .35</p>
 *
 * This class represents software languages the can be generated by Geppetto</br>
 * see GpTechnicalLanguageTypesConstants for a list of languages supported</p>
 *  
 */


public class GpTechnicalLanguageTypes {
	
	
	private long id;
	private String description;
	
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	
	
	
	

}
